### ISSUE TITLE
App Fails When There Is Not Enough Data to Fill Class Breaks

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/dockless#15]
When we use simple stats to create the data classes (aka Jenks breaks), there has to be at least as many data points as classes. If not, simple stats throws an error:
```
Uncaught (in promise) Error: cannot generate more classes than there are data values
    at Object.t.ckmeans (ckmeans.js:221)
    at jenksBreaks (map.js:276)
    at getPaint (map.js:233)
    at addFeatures (map.js:138)
    at map.js:198
```

**Comment by johnclary** [comment]
We could dynamically reduce the number of classes, but they're also hard-coded in [`getPaint`](https://github.com/cityofaustin/dockless/blob/ca0a108721caa2f28cb6fba6246430e36d457946/js/map.js#L235), so that will need to be reworked as well.

**Comment by mateoclarke** [comment]
I'm seeing this bug manifest when I try to filter trip data by `mode=bike`

![screen shot 2018-11-02 at 12 49 28 pm](https://user-images.githubusercontent.com/5697474/47931787-dcc61180-de9d-11e8-97dd-11d534d1e779.png)
