### ISSUE TITLE
Known bug in mapbox-gl-draw, breaks touch events

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/dockless#48]
On mobile browsers, MapboxDraw blocks touch events from firing. This is a documented bug with an open PR that may address the problem: https://github.com/mapbox/mapbox-gl-draw/issues/617

I started trying to take the suggestion from a fellow civic coder @chriswhong:
https://github.com/mapbox/mapbox-gl-draw/issues/617#issuecomment-345586149
https://github.com/NYCPlanning/labs-factfinder/pull/203/files
https://github.com/NYCPlanning/labs-zola/pull/415/files

The solution would be to manually add and remove the controls from the map instance. I started to play with this by adding `docklessMap.map.removeControl(docklessMap.Draw);` to the last line of the `getData` function and it worked. But to rethink the logic of how and when we re-instantiate draw controls, got complex so I'll save it for later.

For now, mobile devices have one less feature. They can't click on a hex cell to see the trip count for that cell.

**Comment by mateoclarke** [comment]
Thinking through a solution, here's an idea: 
- mapbox-gl-draw is instantiated when the map loads like normal
- when the either of the draw buttons are clicked (point or polygon), then a user clicks one point or draws a polygon on the map, and we go get data and render hexes on the map, the last thing we do is remove the mapbox-gl-draw controls from the map.
- Now hexes are active, draw is disabled, and users can click around no problem. In this state, we add a button to the top that prompts the user to clear the map data, pick a new point, etc. Clicking this button, clears map data just as we currently do in `clearMapOnEscEvent` and it re-instantiates mapbox-gl-draw and adds the controls back to the map.

This would be a hack, but maybe it works.

**Comment by ayoung012** [comment]
Thank you for finding a work-around for this! Is currently causing me grief.
