### ISSUE TITLE
Add Legend to Side Panel

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/dockless#59]
The map needs a legend. Our styling is dynamically generated with each API request, so this would also need to drive the legend.

**Comment by mateoclarke** [comment]
Might also be good to add a legend description for height of hexagonal prisms. 5 trips = 1 meter (assuming we go with my PR #73)

**Comment by mateoclarke** [comment]
- absolute number of trips dynamically updates based on jenks break value.
