### ISSUE TITLE
Tooltip for ptz control

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/dockless#60]
I love the tooltips! What do we think about adding a tooltip to the point/tilt/zoom control?
 
![image](https://user-images.githubusercontent.com/14793120/49183781-5f1de600-f323-11e8-96b1-0414dd470495.png)

**Comment by mateoclarke** [comment]
seems chill. what help text do you suggest on the tooltip?

**Comment by johnclary** [comment]
`Click + drag here to tilt the map`

?
