### ISSUE TITLE
Revisit Color Scale

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/dockless#71]
PIO commented that the color scale was confusing in that it was not easy to tell which color was represented the highest values. IIRC we're using color brewer's `9-class YlOrRd`.

**Comment by johnclary** [comment]
sweet, you can link to scales now:
http://colorbrewer2.org/#type=sequential&scheme=YlOrRd&n=9

**Comment by mateoclarke** [comment]
Let's expect the legend to help with this and keep an ear out for this feedback to be repeated.

**Comment by mateoclarke** [comment]
Going to close this out now that the legend is merged to master but we should reopen or create a new issue if we get more feedback that the color scaling is not intuitive.
