### ISSUE TITLE
address mapbox API limit concerns

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/dockless#8]

**Comment by johnclary** [comment]
Mapbox allows 50k map views per month for free. At the moment we've gone through 5k views through 15 days. Should we worry about hitting our limit? 

Possible solutions:
1. [Pay for mapbox](https://www.mapbox.com/pricing/)

2. Stand up our own vector tile server. 
- [Tegola](https://github.com/go-spatial/tegola)
- [Tileserver GL](https://github.com/klokantech/tileserver-gl)

3. Find a freely-hosted vector tile service. E.g., Esri? (http://www.arcgis.com/home/item.html?id=3e1a00aeae81496587988075fe529f71)

**Comment by johnclary** [comment]
submitted a request to pre-pay for $300 of mapbox usage. that'll cover 600k map views in addition to the monthly base of $50. considering the time/effort required to set up our own tile server, i think this cost is reasonable (for now).

**Comment by johnclary** [comment]
let's leave this open until the purchase is approved and paid for.

**Comment by johnclary** [comment]
mapbox payment in place. we've pre-paid for $300 of usage.
